[WIP] Add dependency injections
arjavibahety/SpsTeam8 pull request #54
Opened 2020-07-29 06:15 UTC by arjavibahety

2020-07-29 07:09 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/MyGuiceServletConfig.java
> +public class MyGuiceServletConfig extends GuiceServletContextListener {
rename this to GuiceConfig

2020-07-29 12:40 UTC, arjavibahety commented on webproject/src/main/java/com/google/sps/servlets/MyGuiceServletConfig.java
> +public class MyGuiceServletConfig extends GuiceServletContextListener {
okay!

2020-07-30 15:03 UTC, kevinluvian requested changes
This PR is too big, please consider leaving this PR as it is, and start a new branch to modify only 1-2 servlets in 1 PR.

Also, please add tests for all the files added.

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/CloseRoomServiceImpl.java
> +    public long getTimestamp() {
this is a very simple function, not re-used in this package, but probably used in other files.
You should create a new file like TimestampUtil for this and inject it to this file using dependency injection

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/BlobstoreServiceImpl.java
> +public class BlobstoreServiceImpl implements BlobstoreService {
rename this to GetImageUploadUrlService

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/BlobstoreServiceImpl.java
> +    public long getTimestamp() {
ditto

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/BlobstoreServiceImpl.java
> +        BlobstoreResponse.Builder blobstoreResponse = BlobstoreResponse.newBuilder();
you can return immediately
```
return X.newBuilder().setY().setZ().build();
```

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/BlobstoreServiceImpl.java
> +        com.google.appengine.api.blobstore.BlobstoreService blobstoreService = BlobstoreServiceFactory.getBlobstoreService();
please import com.google.appengine.api.blobstore.BlobstoreService
and move this as class instance

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/CloseRoomServiceImpl.java
> +        CloseRoomResponse.Builder closeRoomResponse = CloseRoomResponse.newBuilder();
ditto return immediately

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/EntryServlet.java
> +        if (entryService.getAuthenticationHandler().isUserLoggedIn()) {
I think for this part, it is not necessary to have entryService, as the code is too simple

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/EntryServiceImpl.java
> +    public AuthenticationHandler getAuthenticationHandler() {
code is too simple, we don't need this part

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/GetJoinServiceImpl.java
> +        String url = "https://summer20-sps-47.firebaseio.com/UserRoom.json?orderBy=%22userEmailRoom%22&equalTo=%22"
use StringBuilder

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/GetJoinServlet.java
> +            FirebaseOptions options = getJoinService.getFirebaseOptions();
Firebase code should be put in one file, put this init() in the constructor, and let other files use it as dependency injection

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +    public AuthenticationHandler getAuthenticationHandler() {
change to use DI

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +    public FirebaseOptions getFirebaseOptions() throws IOException {
ditto. should be on separate file

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +public class PostJoinServiceImpl implements PostJoinService {
rename the service as JoinRoomService

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +public class PostJoinServiceImpl implements PostJoinService {
JoinRoomService is better naming because it can explain that this service is used for user who wanted to join a room, rather than PostJoinService which doesnt explain join what, and why have Post there

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +                .setValueAsync(new UserRoom(userEmail, postJoinRequest.getRoomId()));
use setValue here so that the process is synchronous

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +        PostJoinResponse.Builder postJoinResponse = PostJoinResponse.newBuilder();
ditto chained builder

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/GetJoinServiceImpl.java
> +    public User getCurrentUser() {
can be private? and may not even necessary seeing how simple is the code

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/GetJoinServiceImpl.java
> +    public AuthenticationHandler getAuthenticationHandler() {
use DI

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/GetJoinServiceImpl.java
> +    public long getTimestamp() {
ditto use timestamputil and DI

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/LandingServiceImpl.java
> +    public String getParsedHtmlString() throws IOException {
as the code is quite simple we might not need this file

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +    public User getCurrentUser() {
ditto may not necessary

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/PostJoinServiceImpl.java
> +    public long getTimestamp() {
ditto separate file and DI

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/TextMessageServiceImpl.java
> +    public FirebaseOptions getFirebaseOptions() throws IOException {
ditto

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/TextMessageServiceImpl.java
> +                .setValueAsync(new Message(getUsername(), message, "text"));
ditto use setValue for sync

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/TextMessageServiceImpl.java
> +        TextMessageResponse.Builder textMessageResponse = TextMessageResponse.newBuilder();
ditto chained response

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/TextMessageServiceImpl.java
> +    public long getTimestamp() {
ditto move to util

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/interfaces/BlobstoreService.java
> +    public BlobstoreProtoc.BlobstoreResponse execute() ;
ditto import BlobstoreProtoc.BlobstoreResponse

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/CloseRoomServlet.java
> +        CloseRoomRequest.Builder closeRoomRequest = CloseRoomRequest.newBuilder();
ditto chained builder

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/GetJoinServlet.java
> +        GetJoinRequest.Builder getJoinRequest = GetJoinRequest.newBuilder();
ditto chained builder

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/GetJoinServiceImpl.java
> +    public String execute(GetJoinRequest getJoinRequest) throws IOException {
should return GetJoinResponse. This might be a bit complicated since you need to parse the response from firebase first

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/GuiceConfig.java
> +        // serve("/listings").with(LandingServlet.class);
remove deadcode

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/PostJoinServlet.java
> +    public void init() {
ditto

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/PostJoinServlet.java
> +        AuthenticationHandler auth = postJoinService.getAuthenticationHandler();
lets create an AuthenticatedHttpServlet class which have the checking part as default, and abstract doPostAuthenticated/doGetAuthenticated

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/PostJoinServlet.java
> +public class PostJoinServlet extends HttpServlet {
lets rename this to JoinRoomServlet

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/PostJoinServlet.java
> +        PostJoinRequest.Builder postJoinRequest = PostJoinRequest.newBuilder();
ditto builder

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/TextMessageServlet.java
>      public void init() {
ditto move to other file

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/servlets/TextMessageServlet.java
> +        TextMessageRequest.Builder textMessageRequest = TextMessageRequest.newBuilder();
ditto chained builder

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/GetJoinServiceImpl.java
> +public class GetJoinServiceImpl implements GetJoinService {
add java doc to explain the service

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/CloseRoomServiceImpl.java
> +public class CloseRoomServiceImpl implements CloseRoomService {
javadoc

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/BlobstoreServiceImpl.java
> +public class BlobstoreServiceImpl implements BlobstoreService {
javadoc

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/interfaces/BlobstoreService.java
> +public interface BlobstoreService {
javadoc

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/interfaces/GetJoinService.java
> +public interface GetJoinService {
javadoc

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/interfaces/PostJoinService.java
> +public interface PostJoinService {
javadoc

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/webapp/js/chat-box.js
> +            return response.json();
you can do `.then(response => response.json())` without extra return here

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/services/implementations/GetJoinServiceImpl.java
> +public class GetJoinServiceImpl implements GetJoinService {
rename the GetJoinService to GetUserRoomJoinStatus or anything you feel more appropriate

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/webapp/js/listings.js
> +        let response2 = await fetch("/getJoin?roomId=" + room[0]);
rename the variable to more meaningful name

2020-07-30 15:03 UTC, kevinluvian commented on webproject/src/main/webapp/js/listings.js
> +        url: "/postJoin",
change the API to joinRoom

2020-07-30 15:30 UTC, arjavibahety commented on webproject/src/main/java/com/google/sps/services/implementations/CloseRoomServiceImpl.java
> +    public long getTimestamp() {
Okay!

2020-07-30 15:31 UTC, arjavibahety commented on webproject/src/main/java/com/google/sps/services/implementations/BlobstoreServiceImpl.java
> +public class BlobstoreServiceImpl implements BlobstoreService {
Will do it in the next mini PR

2020-08-09 10:22 UTC, closed without merging