Fix image timestamp displaying UTC time
arjavibahety/SpsTeam8 pull request #64
Opened 2020-08-03 08:51 UTC by bxtsang

2020-08-03 09:08 UTC, kevinluvian requested changes

2020-08-03 09:08 UTC, kevinluvian commented on webproject/src/main/webapp/js/chat-box.js
> +        let date = new Date(snap.time);
rename snap to newMessage

2020-08-03 09:08 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/data/Message.java
> +    private long time;
rename to timestamp

2020-08-03 09:08 UTC, kevinluvian commented on webproject/src/main/webapp/js/chat-box.js
> +        html += `<span class='chat-time'>${hours}:${minutes}</span>`;
should we add date here too?

2020-08-03 09:08 UTC, kevinluvian commented on webproject/src/main/webapp/js/chat-box.js
>          firebase.database().ref('messages/' + roomID).push().set({
change this to send to servlet instead of firebase directly

2020-08-09 13:59 UTC, bxtsang commented on webproject/src/main/webapp/js/chat-box.js
> +        html += `<span class='chat-time'>${hours}:${minutes}</span>`;
added!

2020-08-09 14:22 UTC, kevinluvian requested changes

2020-08-09 14:22 UTC, kevinluvian commented on webproject/src/main/java/com/google/sps/data/Message.java
> +        long currTime = System.currentTimeMillis();
use timestamputil

2020-08-09 19:21 UTC, kevinluvian approved these changes

2020-08-10 07:53 UTC, merged