Create basic chat
arjavibahety/SpsTeam8 pull request #9
Opened 2020-07-09 13:55 UTC by MichaelaTSH

2020-07-10 08:51 UTC, bxtsang commented
Looks good! probably will need to add a room id to the message and validate the user belongs in that room before sending the message, but maybe we can implement that in the next iteration

2020-07-10 11:02 UTC, kevinluvian approved these changes

2020-07-10 11:03 UTC, kevinluvian requested changes

2020-07-10 11:03 UTC, kevinluvian commented on webproject/src/main/webapp/js/chat-script.js
> +    //var profile = auth2.currentUser.get().getBasicProfile();
please remove comments on dead code

2020-07-14 05:43 UTC, kevinluvian requested changes

2020-07-14 05:43 UTC, kevinluvian commented on webproject/src/main/webapp/chat.html
> +    <!-- TODO: Add SDKs for Firebase products that you want to use
remove todo if its finished

2020-07-17 02:52 UTC, closed without merging